[general]
host = "0.0.0.0"
port = 6432

admin_username = "pgbouncer"
admin_password = "admin"

tls_private_key = "/etc/pg_doorman/server.key"
tls_certificate = "/etc/pg_doorman/server.crt"

[pools]

[pools.doorman]
server_host = "postgres"
server_port = 5432
pool_mode = "transaction"

[pools.doorman.users.0]
pool_size = 40
username = "doorman"
# password = "password"
password = "SCRAM-SHA-256$4096:6nD+Ppi9rgaNyP7Iopp5Kg==$kas4oeP+SK/SazbiffEUJsn14RhvKO2vdOnPfarKCEw=:c28R1TLxGh7wERGW8junydkCgYuMBiTld7xJipwG/X4="