# This docker-compose file only for develop and testing.
# You can see example in ./example directory.

services:

  postgres:
    image: postgres:17
    network_mode: "host"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./tests/fixture.sql:/docker-entrypoint-initdb.d/fixture.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true

  pg_doorman:
    network_mode: "host"
    ports:
      - "6433:6433"
    build:
      dockerfile: tests/pg_doorman.Dockerfile
    working_dir: /
    command: /usr/bin/pg_doorman -l info /tests/tests.toml
    volumes:
      - ./tests:/tests
    restart: unless-stopped
    tty: true
    stdin_open: true

  go_test:
    build:
      dockerfile: tests/go_cache.Dockerfile
    working_dir: /
    network_mode: "host"
    profiles:
      - tests
      - tests-go
    volumes:
      - ./tests/go:/tests
    command: /bin/bash -ec 'cd /tests && source ./env && go test -v .'
    restart: no

  python_test:
    build:
      dockerfile: tests/python_cache.Dockerfile
    network_mode: "host"
    profiles:
      - tests
      - tests-python
    volumes:
      - ./tests/python:/tests
    command: /bin/bash -ec 'cd /tests && python ./test_async.py && python ./test_psycopg2.py && python ./test_session_cursors.py'
    restart: no
