# This docker-compose file only for develop and testing.
# You can see example in ./example directory.

services:

  postgres:
    image: postgres:17
    network_mode: "host"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./tests/fixture.sql:/docker-entrypoint-initdb.d/fixture.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true

  pg_doorman:
    network_mode: "host"
    build:
      dockerfile: tests/pg_doorman.Dockerfile
    working_dir: /
    command: /usr/bin/pg_doorman -l info /tests/tests.toml
    volumes:
      - ./tests:/tests
    restart: unless-stopped
    tty: true
    stdin_open: true

  go_test:
    build:
      dockerfile: tests/go_cache.Dockerfile
    working_dir: /
    network_mode: "host"
    volumes:
      - ./tests/go:/tests
    command: /bin/sleep infinity

  python_test:
    build:
      dockerfile: tests/python_cache.Dockerfile
    network_mode: "host"
    volumes:
      - ./tests/python:/tests
    command: /bin/sleep infinity

  nodejs_test:
    build:
      dockerfile: tests/nodejs_test.Dockerfile
    network_mode: "host"
    volumes:
      - ./tests/nodejs:/tests
    command: /bin/sleep infinity

  ruby_test:
    build:
      dockerfile: tests/ruby_test.Dockerfile
    network_mode: "host"
    volumes:
      - ./tests:/tests
    command: /bin/sleep infinity

  dotnet_test:
    build:
      dockerfile: tests/dotnet_test.Dockerfile
    network_mode: "host"
    volumes:
      - ./tests/dotnet:/tests
    command: /bin/sleep infinity
